trigger:
  batch: true
  branches:
    include:
      - master
      - main
      - feature/*
      - fix/*

pr: none

resources:
  repositories:
    - repository: pipeline-library
      type: github
      endpoint: quantum-sec-github
      name: quantum-sec/pipeline-library


jobs:
  - template: templates/jobs/default.yml@pipeline-library
    parameters:
      containerImage: quantumci.azurecr.io/quantum-ci-terragrunt:latest
      runFunctionalTests: false
      buildSteps:
        - script: npm run build
          name: RunTsc
          displayName: Run tsc
          condition: succeeded()
