trigger:
  batch: true
  branches:
    include:
      - master
<<<<<<< HEAD
      - main
=======
>>>>>>> 572dd87 (Initial commit)
      - feature/*
      - fix/*

pr: none

resources:
  repositories:
    - repository: pipeline-library
      type: github
      endpoint: quantum-sec-github
      name: quantum-sec/pipeline-library

jobs:
<<<<<<< HEAD
  - template: templates/jobs/terraform.yml@pipeline-library
    parameters:
      runFunctionalTests: false
=======
  - template: templates/jobs/default.yml@pipeline-library
    parameters:
      containerImage: quantumci.azurecr.io/quantum-ci-terragrunt:latest
>>>>>>> 572dd87 (Initial commit)
